Forsakringskassan/designsystem

package.json

**EDIT**: nu körs både stylish OCH codeframe, så det blir dubbel output. Men det kanske är OK?
Då syns det tydligare i loggen eftersom den också visar raden som strular.
Då ser det ut så här istället:
```
/home/runner/work/designsystem/designsystem/packages/vue/src/components/FTooltip/FTooltip.vue
Error:   5:17  error  element id must not be empty         valid-id
Error:   5:17  error  Attribute "id" has invalid value ""  attribute-allowed-values
✖ 2 problems (2 errors, 0 warnings)
More information:
https://html-validate.org/rules/valid-id.html
https://html-validate.org/rules/attribute-allowed-values.html
error: element id must not be empty (valid-id) at /home/runner/work/designsystem/designsystem/packages/vue/src/components/FTooltip/FTooltip.vue:5:17:
3 |         <div …
```

chore: use codeframe formatter (refs SFKUI-6500)

---

package-lock.json
packages/design/package.json
packages/logic/package.json
packages/vue-labs/package.json
packages/vue/package.json

Så blir vi av med varningarna om att v5.0.0 inte är publicerad.

chore(deps): bump peerDependencies (refs SFKUI-6500)

---

docs/components/sidlayout/FPageHeader.md
etc/vue.api.md
packages/vue/htmlvalidate/elements/components.js
packages/vue/src/components/FPageHeader/FPageHeader.cy.ts
packages/vue/src/components/FPageHeader/FPageHeader.spec.ts
packages/vue/src/components/FPageHeader/FPageHeader.vue

Löser det jag stötte på med skiplink (dock inte att det smäller utan vue-router eller att man inte kan sätta href på logo).
Ändringen är bakåtkompatibel.

feat: use single `skipLink` prop on `FPageHeader` (refs SFKUI-6500)

---

docs/components/framework/IPopupMenu.md
etc/vue.api.md
packages/vue/src/components/FNavigationMenu/FNavigationMenu.vue
packages/vue/src/internal-components/IPopupMenu/IPopupMenu.cy.ts
packages/vue/src/internal-components/IPopupMenu/IPopupMenu.vue
packages/vue/src/internal-components/IPopupMenu/examples/IPopupMenuExample.vue

- chore: move `IPopupMenu` emit docs to `emits` (refs SFKUI-6500)
I feel it is more convenient to have it in the `emits` block so I always know where emits are documented and don't have to search through the file. Since I'm touching this file I'll do it here, but maybe also think about doing this for the rest at some point? Yay/nay?
- refactor: simplify `IPopupMenu` item classes (refs SFKUI-6500)
The double `class` is a bit awkward so make this conform to structure for other components for class bindings.
- fix: fix tabbing issues in `IPopupMenu` (refs SFKUI-6644)
Fixes so that `IPopupMenu` properly handles tab between items and focus when tabbing out from the menu.
- fix: enable focus to `IPopupMenu` while using key nav (refs SFKUI-6622)
`focusedItemKey` was previously used to set focus …

`IPopupMenu` fixes

---

docs/src/docs-theme.scss
docs/src/exp-theme.scss
docs/src/int-theme.scss
package-lock.json
package.json
packages/vue-labs/docs/src/docs-theme.scss
packages/vue-labs/docs/src/exp-theme.scss
packages/vue-labs/docs/src/int-theme.scss

and tilde imports.
Highlight.js styling is now bundled with docs-generator: forsakringskassan/docs-generator#109

chore(deps): drop unused highlight.js dependency (refs SFKUI-6500)

---

packages/css-variables/src/fkui-exp-css-variables.scss
packages/css-variables/src/fkui-int-css-variables.scss
packages/design/src/components/table/_table.scss
packages/vue/src/components/FCrudDataset/FCrudButton.vue
packages/vue/src/components/FCrudDataset/FCrudDataset.spec.ts
packages/vue/src/components/FCrudDataset/FCrudDataset.vue
packages/vue/src/components/FCrudDataset/__snapshots__/FCrudButton.spec.ts.snap
packages/vue/src/components/FCrudDataset/__snapshots__/FCrudDataset.spec.ts.snap
packages/vue/src/components/FInteractiveTable/examples/FInteractiveTableLiveExample.vue

- Lägger till stöd använda tertiära knappar i tabellkolumn med åtgärder
- Fixar fall där knapp-label klipps i tabellkolumn
- Datamängsredigeraren använder tertiära istället för diskreta knappar

fix: teritary buttons in table (refs SFKUI-6710)

---

docs/components/modal/FFormModal.md
docs/functions/functions/modal-functions/confirm-modal.md
docs/functions/functions/modal-functions/form-modal.md
docs/functions/functions/use-modal.md
etc/vue.api.md
packages/vue/src/components/FModal/FFormModal/FFormModal.vue
packages/vue/src/utils/confirm-modal/confirm-modal.ts
packages/vue/src/utils/confirm-modal/index.ts
packages/vue/src/utils/index.ts
packages/vue/src/utils/open-modal/open-modal.ts
packages/vue/src/utils/use-modal.cy.ts
packages/vue/src/utils/use-modal.ts

Det kom upp på FE-synk och kunde inte hålla fingrarna i styr.
Möjliggör att använda modal-funktionerna med composition:
```html
<script setup>
const { confirmModal } = useModal();
async function onClickButton() {
const confirmed = await confirmModal({ content: "Är du säker att du vill ..." });
if (confirmed) {
/* do dangerous but confirmed action */
}
}
</script>
```

feat: new `useModal()` composable for using modals with composition API

---

docs/components/load/FLoader.md
etc/vue.api.md
packages/vue/src/components/FLoader/FLoader.spec.ts
packages/vue/src/components/FLoader/FLoader.vue

Underlättar om man skapar upp en temporär applikation med en `FLoader` medans resterande filer/data hämtas. (Eftersom det då är lite klumpigt att sätta `config.teleportTarget` först till något provisoriskt)
Återstår:

feat: new prop `teleport` on `FLoader` to override default teleport target

---

packages/css-variables/src/fkui-exp-css-variables.scss
packages/css-variables/src/fkui-int-css-variables.scss

Ändrar  till vit bakgrundsfärg i standardmodalens (och formulärsmodalens)  list.

fix: modal shelf color (refs SFKUI-6500)

---

packages/vue/src/components/FCrudDataset/FCrudDataset.spec.ts
packages/vue/src/components/FCrudDataset/__snapshots__/FCrudDataset.spec.ts.snap

Störde mig på varningarna i jest testet för `FCrudDataset`:
`[Vue warn]: <tr> cannot be child of <table>, according to HTML specifications. This can cause hydration errors or potentially disrupt future functionality.`
Åtgärdade varningen och körde prettier på html-blocket.

test: fix table structure follow specification (refs SFKUI-6500)

---

etc/vue.api.md
packages/vue/src/components/FCheckboxField/__snapshots__/FCheckboxGroup.spec.ts.snap
packages/vue/src/components/FFieldset/FFieldset.vue
packages/vue/src/components/FFieldset/__snapshots__/FFieldset.spec.ts.snap
packages/vue/src/components/FRadioField/__snapshots__/FRadioGroup.spec.ts.snap

Tooltip on [`FFieldset`](https://forsakringskassan.github.io/designsystem/latest/components/input/fradiofield.html) is broken since v5.40.0:
This PR fixes this issue but NVDA will present this slightly different to the screenreader:
**Före**:
**Efter**:
Skillnaden är att den tidigare läste upp det som två olika meddelanden där man måste pila mellan dem medans nu blir det direkt i ett och samma meddelande.
Det är samma beteende i vanliga inmatningsfält med `FLabel` och kollade i äldre FKUI-versioner och så har det varit tidigare på `FLabel` också. Så nu är det konsekvent mellan `FLabel` och `FFieldset` iaf, men om det är rätt eller fel låter jag vara osagt.

fix: fix tooltip in fieldset (refs SFKUI-6500)

---

docs/components/modal/FModal.md
etc/vue.api.md
packages/vue/src/components/FModal/FConfirmModal/FConfirmModal.vue
packages/vue/src/components/FModal/FModal.cy.ts
packages/vue/src/components/FModal/FModal.vue

Efter diskussioner irl kommer här en idé till lösningsförslag när konsumenter utav modalen själv vill definera vilket element som skall få focus när modalen släcks.
Vårt konkreta use case är att vi har en modal på en "Ta bort"-knapp, där knappen helt enkelt försvinner när elementet är borttaget. Vi vill därmed sätta focus på nåt annat element.
jag började enkelt med en boolean för detta, vet att det fanns förslag att ha det som ett objekt istället, tar tacksamt emot feedback på ändringar. :-)
Har medvetet valt att inte skriva nåt i dokumentationen tills jag vet om detta kandiderar att mergas eller inte.

feat: fmodal focus strategy (refs SB-4982)

---

packages/vue/src/components/FList/FList.spec.ts
packages/vue/src/components/FList/FList.vue

If the user sets a row to be active, then after that it is not possibe to reset active item to undefined

fix: fix resetting active item back to undefined (refs SFKUI-6941)

---

packages/vue/src/components/FNavigationMenu/FNavigationMenu.vue

If the `routes` prop is missing from `FNavigationMenu` the application crashes:
```vue
<script setup>
import { FNavigationMenu } from "@fkui/vue"
</script>
<template>
<f-navigation-menu></f-navigation-menu>
</template>
```
```
local.ts:19 [Vue warn]: Missing required prop: "routes" 
at <FNavigationMenu> 
at <App>
```
```
index.html:12 TypeError: Cannot read properties of undefined (reading 'map')
at Proxy.items (FNavigationMenu.vue:205:32)
at Proxy._sfc_render (FNavigationMenu.vue:5:41)
```
Which crashes the application:

fix: fix wrong runtime error when missing `routes` prop on `FNavigationMenu` (refs SFKUI-6500)

---

docs/components/validation/examples/PersonnummerNotSameExample.cy.ts
docs/components/validation/examples/PersonnummerNotSameExample.vue
docs/components/validation/examples/PersonnummerOlderExample.cy.ts
docs/components/validation/examples/PersonnummerOlderExample.vue
docs/components/validation/examples/PersonnummerYoungerExample.cy.ts
docs/components/validation/examples/PersonnummerYoungerExample.vue
docs/components/validation/validators.md

- https://forsakringskassan.github.io/designsystem/pr-preview/pr-144/components/validation/validators.html#personnummer_inte_samma_personnummernotsame
- https://forsakringskassan.github.io/designsystem/pr-preview/pr-144/components/validation/validators.html#personnummer_aldre_personnummerolder
- https://forsakringskassan.github.io/designsystem/pr-preview/pr-144/components/validation/validators.html#personnummer_yngre_personnummeryounger

docs: added documentation for personnummer validators (refs KDK-48741)

---

docs/functions/functions/modal-functions/form-modal.md
etc/vue.api.md
packages/vue/src/utils/form-modal/form-modal.spec.ts
packages/vue/src/utils/form-modal/form-modal.ts
packages/vue/src/utils/form-modal/modal-options.ts

Remove the beforeSubmit prop from formModal since it could overwrite beforeSubmit specified on the actual modal.

fix: remove unnecessary beforeSubmit (refs SB-4982)

---

packages/design/src/components/modal/_modal.scss
packages/vue/src/components/FModal/FModal.spec.ts
packages/vue/src/components/FModal/FModal.vue

Applications that scopes all styling from FKUI prevents some global styling. By inlining the global open modal styling it's no longer an issue.
If the styling is not applied, the user can scroll the page background when a modal is open.

fix: inline global modal styling (refs SFKUI-6500)

---

packages/vue/src/components/FModal/FModal.cy.ts
packages/vue/src/components/FModal/FModal.vue

For other focus strategies, the consumer is responsible for focus and scroll when modal is closed.

fix: scroll on modal close when `focus="on"` (fixes #187)

---

packages/vue/src/components/FWizard/FWizardStep.vue

la till attributen för stepNumber och totalStep på fel slot, så tar bort från `error-message` och lägger till på `cancel-button-text`.

fix: stepNumber for cancel button slot in FWizardStep (refs SFKUI-6500)

---

packages/vue/src/components/FCheckboxField/FCheckboxField.spec.ts
packages/vue/src/components/FRadioField/FRadioField.spec.ts
packages/vue/src/components/FSelectField/FSelectField.spec.ts
packages/vue/src/components/FTextField/FTextField.spec.ts
packages/vue/src/components/FTextField/extendedTextFields/FEmailTextField/FEmailTextField.spec.ts
packages/vue/src/components/FTextField/extendedTextFields/FNumericTextField/FNumericTextField.spec.ts
packages/vue/src/components/FTextField/extendedTextFields/FPhoneTextField/FPhoneTextField.spec.ts

`wrapper.get("input")` ger `HTMLInputElement` direkt (precis som att `document.querySelector("input")` gör det). Så meningslöst att casta.
Har säkert inte alltid varit så men det är så nu.

refactor: remove unnecessary cast (refs SFKUI-6500)

---

generate-docs.mjs
internal/serve/lib/cli.js
internal/serve/lib/serve.js
package.json

Ändrar så servern som hostar dokumentationen och kör E2E tester är mindre pratig by default.
* Kör man bara `npm start` eller `fkui-serve` så visas bara fel (HTTP 4xx och 5xx).
* Kör man `npm start -- --verbose` eller `fkui-serve --verbose` så visas allt som tidigare, dvs alla requests inkl HTTP 200 och 304.
* Finns också `--silent` för att tysta den helt.
Tror inte det är vanligt att man behöver använda någon utav flaggorna men de finns där iaf.

build: fkui-serve less verbose output unless using --verbose

---

docs/accessibility.md

Nästkommande version av `@forsakringskassan/docs-generator` kommer falera byggen som använder okända attribut:
```
Unknown attribute "hidden" in "docs/accessibility.md"
3 | name: accessibility
4 | layout: pattern
> 5 | hidden: true
| ^^^^^^ Did you mean to use "visible"?
6 | ---
7 |
8 | ## Tillgänglighet för webbplats
```

docs: fix invalid attribute (refs SFKUI-6500)

---

etc/vue.api.md
packages/vue/htmlvalidate/elements/internal-components.js
packages/vue/src/internal-components/IPopup/IPopup.cy.ts
packages/vue/src/internal-components/IPopup/IPopup.spec.ts
packages/vue/src/internal-components/IPopup/IPopup.vue

Nu är ju detta typ brytande fast det är en I-komponent. Ska vi använda `feat` eller är `refactor` ok? Med i migreringsguiden?
Jag röstar för att vi är hårda med att vi kan ändra I-komponenter och att det är på konsumentens ansvar.

refactor: remove deprecated `alwaysInline` prop from `IPopup`

---

docs/components/FTooltip.md
docs/components/input/examples/ComboboxExample.vue
docs/styles/examples/CompareDensity.vue
etc/vue.api.md
packages/vue/htmlvalidate/elements/components.js
packages/vue/src/components/FCheckboxField/FCheckboxField.cy.ts
packages/vue/src/components/FCheckboxField/examples/FCheckboxFieldLiveExample.vue
packages/vue/src/components/FDatepickerField/examples/FDatepickerFieldLiveExample.vue
packages/vue/src/components/FFieldset/examples/FFieldsetChipLiveExample.vue
packages/vue/src/components/FFieldset/examples/FFieldsetDefault.vue
packages/vue/src/components/FLabel/examples/FLabelLiveExample.vue
packages/vue/src/components/FOutputField/examples/FOutputFieldExample.vue
packages/vue/src/components/FRadioField/FRadioField.cy.ts
packages/vue/src/components/FRadioField/examples/FRadioFieldLiveExample.vue
packages/vue/src/components/FSelectField/FSelectField.cy.ts
packages/vue/src/components/FSelectField/examples/FSelectFieldLiveExample.vue
packages/vue/src/components/FStaticField/examples/FStaticFieldTooltipDescription.vue
packages/vue/src/components/FTextField/examples/FTextFieldLiveExample.vue
packages/vue/src/components/FTextField/extendedTextFields/FSearchTextField/FSearchTextField.cy.ts
packages/vue/src/components/FTextareaField/FTextareaField.cy.ts
packages/vue/src/components/FTextareaField/examples/FTextareaFieldLiveExample.vue
packages/vue/src/components/FTooltip/FTooltip.cy.ts
packages/vue/src/components/FTooltip/FTooltip.spec.ts
packages/vue/src/components/FTooltip/FTooltip.vue
packages/vue/src/components/FTooltip/examples/FTooltipLiveExample.vue
packages/vue/src/pageobject/FCheckboxGroup.pageobject.cy.ts
packages/vue/src/pageobject/FFieldset.pageobject.cy.ts
packages/vue/src/pageobject/FRadioGroup.pageobject.cy.ts
packages/vue/src/pageobject/FTooltip.pageobject.cy.ts

BREAKING CHANGE: FTooltip now requires a `headerTag` if it has a header-slot.
I de fall tooltip har header men vi inte angett header-tag så har den tidigare använt default `div`, vilket sällan blir rätt.
Därför har vi nu gjort det obligatoriskt att ange header-tag om man har en header, för att se till så det blir semantiskt korrekt.

fix!: update FTooltip to require headerTag if header exists (refs SFKUI-6972)

---

docs/functions/config.md
docs/gettingstarted/migration/migrating-to-v6.md
packages/vue/src/components/FModal/FFormModal/FFormModal.vue
packages/vue/src/config/config.ts

BREAKING CHANGE: default `buttonOrder` is now `RIGHT_TO_LEFT`.

feat!: change default `buttonOrder` to `RIGHT_TO_LEFT` (refs SFKUI-6500)

---

docs/components/links/entrypoint.md
docs/gettingstarted/migration/migrating-to-v6/design.md
packages/design/src/components/entrypoint/_entrypoint.scss
packages/vue/src/design-component-tests/entrypoint/examples/EntrypointLiveExample.vue

BREAKING CHANGE: Consumers of this component need to define their disered width.

feat: entrypoint always uses full width (refs SB-4982)

---

packages/design/src/core/helpers/accessibility/_focus.scss
packages/design/src/core/mixins/_focus.scss

Lagt till en transparent fokusram (outline) som används som fokusram i högkontrastläge på alla komponenter.

fix: focus in highcontrast mode (refs SFKUI-6909)

---

packages/vue/src/components/FDatepickerField/FDatepickerField.vue

Tar bort användningen av `v-on.native` från `FDatepickerField`.
Vad jag ser så gör den ingenting i dagsläget då modifiern är borttagen och Vue nu sätter native event listener på rot-elementet då komponenten inte har en matchande emit.
[v-on.native modifier removed](https://v3-migration.vuejs.org/breaking-changes/v-on-native-modifier-removed.html)
_"... Vue will now add all event listeners that are not defined as component-emitted events in the child as native event listeners to the child's root element ..."_

refactor: remove `v-on.native` modifier (refs SFKUI-6500)

---

internal/vue-sandbox/src/local.scss
internal/vue-sandbox/src/local.ts
internal/vue-sandbox/vite.config.ts
packages/vue-labs/src/local.scss
packages/vue-labs/src/local.ts
packages/vue/src/local.scss
packages/vue/src/local.ts

This issue arised when upgrading to Vite6.
The solution is to not configure any prebundle optimization.
Vite detects internal packages and since they are esm packages nothing more is required.

chore: in sandbox devmode detect internal package updates

---

packages/design/src/components/table/_table.scss

fix: fix action buttons wrapping in `FInteractiveTable`

---

etc/vue-labs.api.md
etc/vue.api.md
packages/vue/src/components/FTextField/FTextField.spec.ts
packages/vue/src/components/FTextField/FTextField.vue
packages/vue/src/components/FTextField/extendedTextFields/FEmailTextField/FEmailTextField.vue
packages/vue/src/components/FTextField/extendedTextFields/FPhoneTextField/FPhoneTextField.vue
packages/vue/src/components/FTextField/extendedTextFields/FSearchTextField/FSearchTextField.vue
packages/vue/src/components/FTextField/useTextFieldSetup.ts

Ändrar så att man kan använda `null` till `FTextField` `v-model` samt relaterade komponenter.

fix: text field components allow null model value (refs SFKUI-7076)

---

packages/vue/src/components/FInteractiveTable/FInteractiveTable.cy.ts
packages/vue/src/components/FInteractiveTable/FInteractiveTable.vue

Fixar så att vilka kryssrutor som är valda i `FInteractiveTable` uppdateras när `v-model` ändras.
Dokumentation om `selectable` grejer kommer i annan PR.

fix: `FInteractiveTable` set selected on `v-model` change (fixes SFKUI-7052)

---

docs/components/table-and-list/FList.md
docs/components/table-and-list/table.md
etc/vue.api.md
packages/vue/htmlvalidate/elements/components.js
packages/vue/src/components/FDataTable/FDataTable.spec.ts
packages/vue/src/components/FDataTable/FDataTable.vue
packages/vue/src/components/FInteractiveTable/FInteractiveTable.spec.ts
packages/vue/src/components/FInteractiveTable/FInteractiveTable.vue
packages/vue/src/components/FInteractiveTable/useExpandableTable.ts
packages/vue/src/components/FList/FList.spec.ts
packages/vue/src/components/FList/FList.vue
packages/vue/src/utils/internal-key.spec.ts
packages/vue/src/utils/internal-key.ts

Ändrar så att `keyAttribute` inte är obligatorisk för:
- `FList`
- `FDataTable`
- `FInteractiveTable`
Todo:

optional `keyAttribute`

---

docs/gettingstarted/migration/migrating-to-v6/cypress-pageobjects.md
etc/vue-labs.api.md
etc/vue.api.md
packages/test-utils/jest.d.ts
packages/test-utils/package.json
packages/test-utils/src/matchers/augmentations.ts
packages/test-utils/src/matchers/index.ts
packages/tsconfig/presets/tsconfig-vue.json

För att matcha vad mallprojekten behöver. Kräver att Forsakringskassan/vite-lib-config#48 är merged och released innan detta lirar.
Slänger med en dokumentationsfix som @OlofFredriksson rapporterade också.

fix: use moduleResolution bundler instead of node16

---

packages/design/src/components/table/_table.scss

Sätter kolumnrubriken till att alltid vara vänsterställd.

feat: add styling `text-align: left` on component `th` (fixes SFKUI-7151)

---

packages/design/src/components/entrypoint/_entrypoint.scss
packages/design/src/components/entrypoint/_variables.scss

- New styling for the entrypoint (not using button-styling).
- Added semantic tokens for colors.
- No CSS to set the icon color (the icon uses currentColor). To support forced-colors mode.

feat: update entrypoint with tokens  (refs SFKUI-7040)

---

etc/logic.api.md
packages/date/src/locale.ts
packages/logic/src/dom/focus.ts
packages/logic/src/index.ts
packages/logic/src/services/ElementIdService/ElementIdService.ts
packages/logic/src/services/ElementIdService/index.ts
packages/logic/src/services/PersistenceService/PersistenceService.ts
packages/logic/src/services/PersistenceService/index.ts
packages/logic/src/services/TranslationService/TranslationService.ts
packages/logic/src/services/TranslationService/index.ts
packages/logic/src/services/ValidationService/FieldsetValidationHandler.spec.ts
packages/logic/src/services/ValidationService/ValidationService.blackbox.spec.ts
packages/logic/src/services/ValidationService/ValidationService.spec.ts
packages/logic/src/services/ValidationService/ValidationService.ts
packages/logic/src/services/ValidationService/Validators/index.ts
packages/logic/src/services/ValidationService/index.ts
packages/logic/src/services/index.ts
packages/vue-labs/src/components/XTimeTextField/XTimeTextField.spec.ts
packages/vue/src/components/FDatepickerField/FDatepickerField.spec.ts
packages/vue/src/components/FPageLayout/webcomponent/page-layout.ts
packages/vue/src/components/FTextField/FTextField.spec.ts
packages/vue/src/components/FTextField/extendedTextFields/FEmailTextField/FEmailTextField.spec.ts
packages/vue/src/components/FTextField/extendedTextFields/FPercentTextField/FPercentTextField.spec.ts
packages/vue/src/components/FTextField/extendedTextFields/FPhoneTextField/FPhoneTextField.spec.ts
packages/vue/src/plugins/validation/ValidationPlugin.ts

Given a simple testcase:
```ts
import { findCookie } from "@fkui/logic"
```
When bundled with esbuild the final bundle size is a staggering **96kb**. Rollup performs similarly.
This PR reduces the amount to "only" 40kb by:
* Removing the global registration of validators instead relying on `ValidationPlugin`. This is semi-breaking, I would argue though that there is no consumer using validators purely from `@fkui/logic` as it is such a pain in the ass to do so. If they do they must now use `availableValidators` and manually register. This removes the biggest chunk of the bundle.
* Using the `/* @__PURE__ */` annotation on as many globals as possible. This includes the awfule singletons we use, the pattern is by design not treeshakable but this mitigates it. The annotation is supported by …

Better treeshaking of @fkui/logic

---

packages/design/src/components/table/_table.scss

Länk: https://designsystem.forsakringskassan.se/latest/components/table-and-list/table.html#interaktiv_tabell
> Safari on iOS treats `visibility: collapse` like `hidden`, leaving a white gap.
_Källa: https://developer.mozilla.org/en-US/docs/Web/CSS/visibility#browser_compatibility_

fix: collapsed expandable rows in `FInteractiveTable` shown as white gaps in iOS browsers (fixes SFKUI-6984)

---

cypress/tsconfig.json
vite.config.mts

Similar to #282 but for Cypress, solves issues with multiple versions on `@fkui/vue` being pulled into test cases (causing issues with global state)

build(cypress): fix incorrectly cypress/vite prebundling monorepo packages (refs SFKUI-6500)

---

docs/src/docs-theme.scss

fixes #394
Före:
Efter:
---
Det grå sträcket under alla länkar får nu samma svarta färg som textfärgen istället för att de behåller den vita färgen. Marginalen runt byt version är justerad att matcha andra länkar.
Personligen tycker jag det ser ganska fult ut men tänker att det blir bättre (konsekvent) så här och sen får gärna någon annan justera så det faktiskt ser snyggt ut också.
Trodde att det här var löst för FPageHeader men där har vi inga text-länkar och därför ingen styling för det. Om konsumenten slottat in det så ser det trasigt ut (har för mig vi råkade ut för det i texteditorn och fix lösa det i applikationen).

docs: consistent look of footer links (fixes SFKUI-7183)

---

packages/vue/src/components/FInteractiveTable/examples/FInteractiveTableLiveExample.vue

Denna PR är splittrad från #458 som exploderade när jag försökte mig på `git rebase`.
Lagt till alternativet `Visa aktiv rad` i liveexemplet för interaktiv tabell (https://forsakringskassan.github.io/designsystem/pr-preview/pr-470/components/table-and-list/table.html#interaktiv_tabell)

docs: add option `Visa aktiv rad` in interactive table live example (refs SFKUI-7153)

---

packages/vue/src/components/FDataTable/examples/FDataTableLiveExample.vue
packages/vue/src/components/FInteractiveTable/examples/FInteractiveTableLiveExample.vue

Denna PR är splittrad från #458 som exploderade när jag försökte mig på `git rebase`.
Grupperat alternativ för dessa liveexempel:
- Datatabell (https://forsakringskassan.github.io/designsystem/pr-preview/pr-469/components/table-and-list/table.html#datatabell)
- Interaktiv tabell (https://forsakringskassan.github.io/designsystem/pr-preview/pr-469/components/table-and-list/table.html#interaktiv_tabell)

docs: group table live example options (refs SFKUI-7153)

---

docs/components/table-and-list/table.md
packages/design/src/components/table/_table.scss

Tar bort styling för `TableScroll.VERTICAL` och `TableScroll.BOTH`.
Denna PR har splittrats ut till #474 och #475.

feat: remove styling for table scroll values `VERTICAL` and `BOTH` (refs SFKUI-7119)

---

docs/components/page-layout/FDetailsPanel.md
docs/components/page-layout/FFixedPane.md
docs/components/page-layout/FMinimizablePanel.md
docs/components/page-layout/FResizePane.md
docs/guides/custom-page-layout.md
etc/docs-manifest.md
etc/vue.api.md
packages/vue/htmlvalidate/elements/components.js
packages/vue/src/components/FDetailsPanel/examples/FDetailsPanelExclusive.vue
packages/vue/src/components/FFixedPane/FFixedPane.ce.vue
packages/vue/src/components/FFixedPane/FFixedPane.scss
packages/vue/src/components/FFixedPane/FFixedPane.vue
packages/vue/src/components/FFixedPane/index.ts
packages/vue/src/components/index.ts

Use this component for fixed size panels in `f-page-layout` (as opposed to `f-resize-pane`).
Especially important when having multiple panels in the same layout slot.

feat: add `f-fixed-pane` component (refs SFKUI-6500)

---

cypress/pageobjects/wizardstep/MyOrderWizardStep.pageobject.ts
docs/templates/partials/selectable-version.html
packages/vue/htmlvalidate/rules/classdeprecated.rule.js
packages/vue/htmlvalidate/rules/classdeprecated.spec.ts
packages/vue/src/components/FCard/FCard.cy.ts
packages/vue/src/components/FDatepickerField/FDatepickerField.vue
packages/vue/src/components/FFileItem/FFileItem.cy.ts
packages/vue/src/components/FLoader/examples/FLoaderExample.vue
packages/vue/src/components/FModal/FFormModal/FFormModal.cy.ts
packages/vue/src/components/FSortFilterDataset/FSortFilterDataset.vue
packages/vue/src/components/FWizard/examples/FWizardExampleAddStep.vue
packages/vue/src/design-component-tests/Button/examples/ButtonButtonGroupFullWidthExample.vue
packages/vue/src/internal-components/IPopupError/IPopupError.vue

**EDIT:** tog bort allt kontroversiellt och nu är det bara testfall, exempel osv som är inkluderat här. Lägger ny PR senare med kontroversiella ändringar.
Regressionstestning:

refactor: remove usage of button--discrete

---

packages/design/src/components/button/_variables.scss
packages/design/src/components/combobox/_variables.scss
packages/design/src/components/select-field/_variables.scss
packages/design/src/components/text-field/_variables.scss
packages/design/src/components/textarea-field/_variables.scss
packages/design/src/core/mixins/_variables.scss
packages/theme-default/src/_semantic-tokens.scss
packages/theme-default/src/deprecated-variables.json
packages/theme-default/src/fkui-css-variables-deprecated.scss

**Added and removed semantic tokens for colors and state disabled.**
New variable:
--fkds-color-border-disabled
Deprecated:
--fkds-color-action-background-disabled
--fkds-color-action-border-disabled
--fkds-icon-color-action-content-primary-disable
Updated Button (and mixin) and Combobox according to above changes.
**Removed all semantic tokens for accent-color.** (not used by any component)

feat: updated semantic tokens for colors (refs SFKUI-7232)

---

packages/vue/src/components/FInteractiveTable/FInteractiveTable.vue
packages/vue/src/components/FInteractiveTable/useExpandableTable.ts

Ändrar fokusbeteendet vid borttaggning av rad så att den fokuserar föregående interagerbara element från den borttagna raden (eller nästa om detta inte existerar).
Har inte fått cypress att fungera för testning av fokuset (visar inget fokus), dock fungerat vid manuell testning.

fix: FInteractiveTable focus correct interactable on delete (fixes SFKUI-5257)

---

packages/design/src/components/chip/_variables.scss
packages/theme-default/src/_semantic-tokens.scss
packages/theme-default/src/deprecated-variables.json
packages/theme-default/src/fkui-css-variables-deprecated.scss

Deprekerat semantiska färgvariabler:
```
--fkds-color-action-background-select-hover
--fkds-color-action-background-select-default
```
Infört nya:
```
--fkds-color-select-background-secondary-default
--fkds-color-select-background-secondary-hover
--fkds-color-select-background-secondary-active
--fkds-color-select-background-secondary-focus
```
Ändrat Chip till att använda ...-secondary-default.

feat: update semantic tokens for select (refs SFKUI-7236)

---

packages/vue/src/components/FSortFilterDataset/FSortFilterDataset.spec.ts
packages/vue/src/components/FSortFilterDataset/FSortFilterDataset.vue

Behåller vald sorteringsordning även om datan uppdateras

fix: `FSortFilterDataset` respect sort attribute after dataset update

---

etc/vue-cypress.api.md
packages/vue/src/components/FInteractiveTable/FInteractiveTable.cy.ts
packages/vue/src/cypress/FInteractiveTable.pageobject.cy.ts
packages/vue/src/cypress/FInteractiveTable.pageobject.ts

Bryter ut lite från test-arbete relaterat till tabell.
Ändrar ej något existerande beteende här utan uppdaterar bara dokumentation och tester för page object för `FInteractiveTable` baserat på hur det fungerar just nu.

test: update `FInteractiveTablePageObject` (refs SFKUI-6500)

---

package.json
scripts/version

Inte provkört det här i ett monorepo så hoppas det lirar men tänker att vi kanske kan testa på en oskyldig fil och testa i releasen och se om det fungerar och anpassa om det inte lirar.

build: support `%version%` as a placeholder in code and documentation

---

packages/design/src/components/label/_label.scss

Åtgärdar #544.
Problemet orsakas av definitionen `width: var(--f-width-full);` i selektorn `.label`.
https://github.com/user-attachments/assets/e399a180-c435-470e-baa9-a1550e27a1f3

fix: unnecessary horizontal scroll bar shown for fieldsets with tooltips (fixes SFKUI-7292)

---

packages/design/src/components/table/_table.scss

Åtgärdar #599.
https://forsakringskassan.github.io/designsystem/pr-preview/pr-602/components/table-and-list/table.html#datatabell

fix: numeric table column headers not right aligned (refs SFKUI-6500)

---

etc/vue.api.md
packages/vue/src/components/FLayoutRightPanel/FLayoutRightPanel.spec.ts
packages/vue/src/components/FLayoutRightPanel/FLayoutRightPanel.vue

Snubblade över denna oanvända metoden (som visade sig användas i testfallet), slänger bort den.

refactor: remove unused method (refs SFKUI-6500)

---

docs/functions/cypress/pageobjects/FBadgePageObject/FBadgePageObject-is-inverted.cy.ts

https://forsakringskassan.github.io/designsystem/pr-preview/pr-614/functions/cypress/pageobjects/FBadgePageObject/is-inverted.html#exempel

test: fix `FBadgePageObject-is-inverted.cy.ts` spelling error (refs SFKUI-6500)

---

packages/vue/src/components/FButton/FButton.vue

`${array}` blir implicit joined med `,` som delimiter men här vill vi överhuvudtaget inte lägga på dubbletterna ändå.
Hittade det när jag slog på `@typescript-eslint/restrict-template-expressions` som då klagar på implicit sträng-konvertering när man försöker skicka in en array till en template literal.
Det känns lite som att det saknas testfall någonstans här dock.

fix: fix redundant classes being added to FButton (refs SFKUI-6500)
