Forsakringskassan/designsystem

docs/accessibility.md
docs/templates/partials/footer.html

Updaterade sidfot med länk till GitHub.
Avstavning av titel på Tillgänglighetsredogörelse.

docs: update footer (refs SFKUI-6761)

---

docs/components/tabell-och-lista/table.md

Annars blir inte komponenterna sökbara och ingen länk till källkod.

docs: properly link table.md to components (refs SFKUI-6500)

---

etc/vue.api.md
packages/vue/src/components/FCrudDataset/FCrudDataset.vue
packages/vue/src/components/FCrudDataset/fcruddataset-data.ts
packages/vue/src/components/FCrudDataset/index.ts
packages/vue/src/components/FCrudDataset/operation.ts
packages/vue/src/components/FDialogueTree/FDialogueTree.vue
packages/vue/src/components/FDialogueTree/FDialogueTreeData.ts
packages/vue/src/components/FDialogueTree/index.ts
packages/vue/src/components/FInteractiveTable/FInteractiveTable.vue
packages/vue/src/components/FInteractiveTable/finteractivetable-data.ts
packages/vue/src/components/FInteractiveTable/index.ts
packages/vue/src/components/FInteractiveTable/useExpandableTable.ts
packages/vue/src/components/FList/FList.vue
packages/vue/src/components/FList/flist-data.ts
packages/vue/src/components/FList/index.ts
packages/vue/src/components/FTableColumn/FTableColumnData.ts
packages/vue/src/components/FTableColumn/index.ts
packages/vue/src/components/index.ts
packages/vue/src/utils/form-modal/form-modal.ts
packages/vue/src/utils/form-modal/index.ts
packages/vue/src/utils/form-modal/modal-options.ts
packages/vue/src/utils/index.ts
packages/vue/src/utils/open-modal/index.ts
packages/vue/src/utils/open-modal/open-modal.ts

Finns några till som behöver fixas men vi kanske kan merga in denna ändå?

Add missing exports

---

CONTRIBUTING.md
README.md
docs/guide/contribute-to-fkds/contributing-developers.md

Uppdatering av readme-filen med text på engelska.
Förtydligat i contributing att dokumentation på webbplatsen ska vara på svenska.

docs: update readme and contributing (refs SFKUI-6797)

---

docs/components/tabell-och-lista/FSortFilterDataset.md

https://forsakringskassan.github.io/designsystem/pr-preview/pr-51/components/tabell-och-lista/fsortfilterdataset.html#forvald_sortering

docs: correct typo in FSortFilterDataset.md

---

packages/vue/htmlvalidate/elements/components.js

Lägger till html-validate reglerna att brickor är ok i en tabellkolumn

chore: support fbadge in table column (refs SFKUI-6842)

---

README.md

Har lagt till "Kontakta oss" med mailadress i Readme-filen både på svenska och engelska.

docs: update readme (refs SFKUI-6878)

---

.github/workflows/build.yml

Ändringen orsakade att "publish test results" tog över 2 timmar.
Behöver undersökas varför och fixas innan den stegas igen.

chore(deps): revert "update mikepenz/action-junit-report action to v5" (refs SFKUI-6500)

---

packages/design/src/components/tooltip/_tooltip.scss
packages/design/src/components/tooltip/_variables.scss

- Semantiska tokens för tooltip
- Ändrad färg på tooltip border

feat: semantic tokens tooltip (refs SFKUI-6920)

---

etc/vue.api.md
packages/vue/src/components/FCard/FCard.vue
packages/vue/src/composables/index.ts
packages/vue/src/composables/useSlotUtils.ts
packages/vue/src/index.ts

Refactor FCard to composition API

refactor: fcard refactored to Composition API (refs SFKUI-6500)

---

CODEOWNERS
etc/vue.api.md
packages/vue/src/components/FBadge/FBadge.vue

FBadge composition API revision efter feedback
Fixade så att tidigare commits inte commitades igen

refactor: use composition api in 'FBadge' (refs SFKUI-6500)

---

cypress/e2e/live-example.cy.ts

E2E-tester kommer att faila tills följande PR´s är mergade:
Samt att varningen om `router-link` i exemplen för FPageHeader åtgärdas:

test: add e2e test to ensure all vue preview examples starts

---

etc/vue.api.md
packages/vue/src/components/FNavigationMenu/FNavigationMenu.cy.ts
packages/vue/src/components/FNavigationMenu/FNavigationMenu.vue
packages/vue/src/internal-components/IPopup/IPopup.cy.ts
packages/vue/src/internal-components/IPopup/IPopup.spec.ts
packages/vue/src/internal-components/IPopup/IPopup.vue
packages/vue/src/internal-components/IPopup/ipopup-data.ts
packages/vue/src/internal-components/IPopup/is-teleport-disabled.ts
packages/vue/src/internal-components/IPopupMenu/IPopupMenu.cy.ts

Ändrar så att `IPopup` beräknar om sin placering istället för att stänga sig själv när man ändrar storlek på fönstret.

refactor: `IPopup` resize recalculate instead of close (refs SFKUI-6672)

---

packages/design/build.mjs

Idag när man gör något fel med css-variabler så får man ett väldigt skrikigt drygt fel:
```
Error: Fallback value not found for variable --foobar
at /path/to/projectsrc/style.scss:1325:5
at failOrWarn (/path/to/project/node_modules/postcss-var-func-fallback/index.js:31:15)
at /path/to/project/node_modules/postcss-var-func-fallback/index.js:56:11
at walk (/path/to/project/node_modules/postcss-value-parser/lib/walk.js:7:16)
at ValueParser.walk (/path/to/project/node_modules/postcss-value-parser/lib/index.js:18:3)
at Declaration (/path/to/project/node_modules/postcss-var-func-fallback/index.js:41:19)
at LazyResult.visitTick (/path/to/project/node_modules/postcss/lib/lazy-result.js:447:16)
at LazyResult.runAsync (/path/to/project/node_modules/postcss/lib/lazy-result.js:275:30)
at async …
```

build: better error messages from postcss (refs SFKUI-6500)

---

docs/components/links/entrypoint.md
packages/vue/src/design-component-tests/entrypoint/examples/EntrypointLiveExample.vue

Ersatt gamla exempel med nytt live exempel

docs: new example entrypoint (refs SFKUI-6500)

---

packages/vue/src/vite-dev/app.vue

Refaktoriserat vue start

---

docs/gettingstarted/about/news.md

Uppdaterade nyheter med information om kombobox.

docs: combox news (refs SFKUI-5885)

---

.github/workflows/docs.yml
.github/workflows/release.yml

Helt otestat, håller tummarna :)
https://docs.github.com/en/actions/sharing-automations/reusing-workflows

ci: automatically deploy new docs after release (refs SFKUI-6500)

---

packages/css-variables/src/_semantic-tokens.scss
packages/design/src/components/chip/_variables.scss
packages/design/src/components/combobox/_variables.scss
packages/design/src/components/select-field/_select-field.scss
packages/design/src/components/select-field/_variables.scss

Uppdaterat komponenten dropplista med nya variabler och "tokens" för färger.

feat: update selectfield with tokens (refs SFKUI-6940)

---

TESTING.md
docs/components/FContextMenu.md
docs/components/FOffline.md
docs/components/FWizard.md
docs/components/group/group.md
docs/components/modal/FFormModal.md
docs/components/table-and-list/FCrudDataset.md
docs/components/validation/FValidationForm.md
docs/functions/config.md
docs/functions/functions/handle-keyboard-focus-navigation.md
docs/functions/functions/mount-component.md
docs/functions/functions/render-slot-text.md
docs/functions/i18next-translate/i18next-provider.md
docs/functions/i18next-translate/i18next.md
docs/functions/plugins/ErrorPlugin.md
docs/functions/plugins/TestPlugin.md
docs/functions/plugins/ValidationPlugin.md
docs/functions/test-utils/vue.md
docs/gettingstarted/use-design-system/getting-started-application.md
docs/guides/validation-and-error-handling/custom-validator.md

Gammal commit som påbörjar att få samtliga exempel kompilerade

docs: fix critical compilation errors in examples (refs SFKUI-6500)

---

fkui.code-workspace

Also updates deprecated configs.

chore: single workspace folder (refs SFKUI-6500)

---

packages/css-variables/src/_deprecated-exp-css-variables.scss
packages/css-variables/src/_deprecated-int-css-variables.scss
packages/css-variables/src/_semantic-tokens.scss
packages/css-variables/src/default-variables.scss
packages/css-variables/src/deprecated-variables.json
packages/css-variables/src/fkui-int-css-variables.scss
packages/design/src/components/button/_button.scss
packages/design/src/components/button/_variables.scss
packages/design/src/core/mixins/_button.scss
packages/design/src/core/mixins/_variables.scss

Added semantic tokens to primary, secondary and tertiary button. Applied tokens for secondary button to the standard button. The discreet button is unchanged.

feat: updated button with semantic tokens (refs SFKUI-6988)

---

docs/gettingstarted/about/news.md
docs/gettingstarted/about/release-plan.md
docs/src/docs-theme.scss

docs: update release plan

---

packages/design/src/components/icon/_icon.scss
packages/design/src/components/icon/_variables.scss
packages/design/src/components/message-box/_message-box.scss
packages/design/src/components/message-box/_variables.scss
packages/theme-default/src/_css-variables.scss
packages/theme-default/src/deprecated-variables.json
packages/theme-default/src/fkui-css-variables-deprecated.scss

Uppdaterat Meddelanderutan (samt ikoner som används i bla Meddelanderutan) med semantiska tokens och nya komponentspecifika variabler.

feat: added semantic tokens to Messagebox (refs SFKUI-6986)

---

CODEOWNERS

- @kristofernilsson no longer works here
- @KrQnan66140124 is not (yet?) a member of the organisation, after being added to the organisation please readd yourself.

codeowners cleanup

---

README.md
docs/gettingstarted/about/release-plan.md
docs/index.md

Uppdaterat sidan På gång med information om release v 6.1.0.
Lagt till länkar på förstasidan och README-filen till sidan På gång.

docs: release update

---

packages/design/src/components/label/_label.scss
packages/design/src/components/label/_variables.scss
packages/theme-default/src/_semantic-tokens.scss

Uppdaterat komponent etikett med semantik tokens för färger.

feat: update label with tokens (refs SFKUI-6835)

---

docs/guides/custom-page-layout.md
packages/vue/src/components/FPageLayout/webcomponent/page-layout.css

[Förhandsgranskning vue-sandbox](https://forsakringskassan.github.io/designsystem/pr-preview/pr-342/vue-sandbox/#/)

feat: set colors on FPageLayout areas (refs SFKUI-6500)

---

packages/vue/src/components/FPageLayout/webcomponent/page-layout.css

Bryter ut denna till en egen commit medans vi granskar den andra PRn

fix: fix `FPageLayout` size on IOS (refs SFKUI-6500)

---

internal/publiccode/index.js
internal/publiccode/package.json
internal/publiccode/prepare.spec.js
package-lock.json
package.json
release.config.js

Nytt internt paket som håller `publiccode.yml` uppdaterad vid release.

ci: new internal package that handles `publiccode.yml` (refs SFKUI-7090)

---

.github/workflows/pr-preview.yml
internal/testbed-page-layout/.browserslistrc
internal/testbed-page-layout/.htmlvalidate.json
internal/testbed-page-layout/LICENSE.md
internal/testbed-page-layout/README.md
internal/testbed-page-layout/elements.json
internal/testbed-page-layout/index.html
internal/testbed-page-layout/package.json
internal/testbed-page-layout/src/App.vue
internal/testbed-page-layout/src/components/XContextBar.vue
internal/testbed-page-layout/src/components/XToolbar.vue
internal/testbed-page-layout/src/components/index.ts
internal/testbed-page-layout/src/local.scss
internal/testbed-page-layout/src/local.ts
internal/testbed-page-layout/src/main.ts
internal/testbed-page-layout/src/router.ts
internal/testbed-page-layout/src/views/XDocumentView.vue
internal/testbed-page-layout/src/views/XJournalView.vue
internal/testbed-page-layout/src/views/XOverviewView.vue
internal/testbed-page-layout/src/views/index.ts
internal/testbed-page-layout/tsconfig.json
internal/testbed-page-layout/vite.config.ts
package-lock.json
packages/vue/src/components/FPageLayout/FPageLayout.vue
packages/vue/src/components/FPageLayout/use-area-data.ts
packages/vue/src/components/FPageLayout/webcomponent/page-layout.ts
scripts/postbuild.js

Direktlänk: https://forsakringskassan.github.io/designsystem/pr-preview/pr-356/testbed-page-layout/#/

Layout testbed

---

internal/publiccode/index.js
internal/publiccode/package.json
internal/publiccode/prepare.spec.js
package-lock.json
package.json
publiccode.yml
release.config.js

Beskrivning av formatet: https://yml.publiccode.tools/schema.core.html

docs: add publiccode.yml (refs SFKUI-6500)

---

docs/components/validation/validators.md
docs/gettingstarted/about/release-plan.md

Uppdateratde text för validator telefonnummer.

docs: update validator text

---

etc/vue.api.md
packages/vue/src/components/FTableColumn/FTableColumn.vue

Bryter ut från annat arbete med tabellkolumn.

refactor: migrate FTableColumn to composition api (refs SFKUI-6500)

---

docs/components/page-layout/FResizePane.md
docs/functions/functions/use-resize.md
docs/guides/custom-page-layout.md
etc/docs-manifest.md
etc/vue.api.md
packages/vue/src/components/FPageLayout/FPageLayout.vue
packages/vue/src/components/FResizePane/FResizePane.ce.spec.ts
packages/vue/src/components/FResizePane/FResizePane.ce.vue
packages/vue/src/components/FResizePane/FResizePane.scss
packages/vue/src/components/FResizePane/FResizePane.vue
packages/vue/src/components/FResizePane/compute-css-value.ts
packages/vue/src/components/FResizePane/examples/CustomPanelExample.vue
packages/vue/src/components/FResizePane/index.ts
packages/vue/src/components/FResizePane/use-resize.ts
packages/vue/src/components/index.ts

refactor: FResizePane provides interface to enable/disable and to show/hide

---

packages/vue/src/components/FCrudDataset/examples/FCrudDatasetSortListExample.vue

Sortera på namn i detta exempel fungerar ej:
https://designsystem.forsakringskassan.se/latest/components/table-and-list/fcruddataset.html#sorterbar_lista

docs: fixed sorting bug in example for FCrudDataset (fixes SFKUI-0000)

---

packages/design/src/components/card/_card.scss
packages/design/src/components/card/_variables.scss

Uppdaterat komponent kort med semantiska tokens.

feat: update card semantic tokens

---

packages/vue/src/components/FCard/FCard.cy.ts
packages/vue/src/components/FCard/FCard.vue
packages/vue/src/components/FCard/examples/FCardValidationExample.vue

Card now ignores child validity events.

fix: card throws error when content is validated (fixes SFKUI-7190)

---

packages/design/src/components/wizard/_variables.scss
packages/design/src/components/wizard/_wizard-step.scss
packages/theme-default/src/_semantic-tokens.scss

Added semantic tokens for colors.
Added support for forced-colors mode.

feat: add semantic tokens for colors to wizard (refs SFKUI-7160)

---

.github/workflows/lint.yml
packages/vue/src/components/FResizePane/FResizePane.ce.vue
packages/vue/src/components/FTextField/FTextField.vue

ci: disallow lint warnings

---

docs/components/FBadge.md
docs/functions/cypress/pageobjects/FBadgePageObject/FBadgePageObject-is-inverted.cy.ts
docs/functions/cypress/pageobjects/FBadgePageObject/FBadgePageObject-is-inverted.md
docs/functions/cypress/pageobjects/FBadgePageObject/FBadgePageObject-is-inverted.vue
docs/functions/cypress/pageobjects/FBadgePageObject/FBadgePageObject-status.cy.ts
docs/functions/cypress/pageobjects/FBadgePageObject/FBadgePageObject-status.md
docs/functions/cypress/pageobjects/FBadgePageObject/FBadgePageObject-status.vue
docs/functions/cypress/pageobjects/FBadgePageObject/FBadgePageObject.cy.ts
docs/functions/cypress/pageobjects/FBadgePageObject/FBadgePageObject.md
docs/functions/cypress/pageobjects/FBadgePageObject/FBadgePageObject.vue
etc/docs-manifest.md

Added documentation for FBadge

docs: fbadge documentation added (refs SFKUI-7023)

---

packages/design/src/components/table/_table.scss

Splittrad från #379.
Åtgärdar ursprungligt problem i SFKUI-7119.

fix: horizontal scroll bar shown when `scroll="vertical"` (fixes SFKUI-7119)

---

packages/design/src/components/list/_list.scss

Liveexempel finns på https://forsakringskassan.github.io/designsystem/pr-preview/pr-476/components/input/fcheckboxfield.html.
Kryssa i alternativen _Inaktiverad_ och _Ram_.

fix: visible hover effect for inactive bordered checkboxes (fixes SFKUI-7214)

---

package-lock.json
packages/icon-lib-builder/README.md
packages/icon-lib-builder/package.json
packages/icon-lib-builder/scripts/build.js

Byggt helt för internt bruk, har en idé om att vi vill kunna sätta upp CSS för tex stackbara varianter som skall återanvändas.

feat: allow SCSS entry in icon lib (refs SB-4982)

---

packages/design/src/internal-components/calendar-navbar/_navbar.scss
packages/vue/src/components/FCalendar/FCalendar.cy.ts
packages/vue/src/components/FDatepickerField/FDatepickerField.cy.ts
packages/vue/src/cypress/ICalendar/Calendar.pageobject.ts
packages/vue/src/internal-components/calendar/ICalendarNavbar.vue

Aktuella komponenter:
- https://forsakringskassan.github.io/designsystem/pr-preview/pr-489/components/input/fdatepickerfield.html
- https://forsakringskassan.github.io/designsystem/pr-preview/pr-489/components/fcalendar.html

feat: update calender navbar styling (refs SFKUI-7243)

---

packages/design/src/components/button/_button.scss
packages/design/src/core/mixins/_button.scss

Added support for forced-colors mode to button icons:
- Removed CSS used to set colors of button icons. 
- Relying on CurrentColor i the svg-icons.

feat: button icon and forced colors  (refs SFKUI-6980)

---

.eslintrc.cjs
packages/icon-lib-builder/bin/build.js
packages/icon-lib-builder/package.json
packages/icon-lib-builder/scripts/build-demo.js
packages/icon-lib-builder/scripts/build.js
packages/icon-lib-builder/scripts/common.js
packages/icon-lib-builder/scripts/generate-index-file.js
packages/icon-lib-builder/scripts/generate-index-file.spec.js
packages/icon-lib-builder/scripts/generate-package-dts.js
packages/icon-lib-builder/scripts/generate-package-dts.spec.js

Finns egentligen mycket kärlek att ge till denna koden men försökte i denna commit att fokusera på konventering till ESM. Gör diffen lite roligare att följa :-)
Lite osäker hur jag testar detta, idéer?

refactor: icon-lib-builder esm (refs SB-4982)

---

packages/design/src/components/checkbox/_checkbox.scss
packages/design/src/components/checkbox/_variables.scss

Infört semantiska tokens på kryssruta och infört stöd för högkontrastläge
Ändrat ikonen från background-image till mask-image för att kunna hantera högkontrastläge på rätt sätt.

feat: added semantic tokens and HCM support on checkbox (refs SFKUI-7178)

---

packages/design/src/components/file-item/_file-item.scss
packages/design/src/components/progressbar/_progressbar.scss
packages/design/src/components/progressbar/_variables.scss
packages/theme-default/src/_css-variables.scss
packages/theme-default/src/deprecated-variables.json
packages/theme-default/src/fkui-css-variables-deprecated.scss

- Uppdaterat progressbar med semantiska variabler för färger.
- Ny visuell design.
- Tagit bort styling av progressbar i file-item.

feat: update progressbar with semantic tokens (refs SFKUI-7273)

---

packages/design/src/components/dialogue-tree/_dialogue-tree.scss
packages/design/src/components/dialogue-tree/_variables.scss

Uppdaterat dialogträd med semantiska tokens för färger.

feat: update semantic tokens dialogue-tree

---

packages/design/src/components/radio-button/_radio-button.scss
packages/design/src/components/radio-button/_variables.scss

Semantiska tokens och stöd för högkontrastläge på radioknapp.
Uppdaterad design med samma färg på border och bakgrund när radioknappen är vald.

feat: semantic tokens and HCM support on radio button (refs SFKUI-7179)

---

docs/gettingstarted/use-design-system/getting-started.md
docs/templates/partials/footer.html

Lagt till länk till https://www.figma.com/@fkds på:
- https://designsystem.forsakringskassan.se/latest/gettingstarted/use-design-system/getting-started.html#designer
- I sidfoten under länk till GitHub

docs: added link to figma library (refs SFKUI-6500)

---

docs/components/framework/IAnimateExpand.md
docs/components/framework/IFlex.md
docs/components/framework/ISkipLink.md
docs/components/framework/about.md
etc/docs-manifest.md

Lagt till ny sida med information om ramverkskomponenter.
Tagit bort status produktionsklar på ramverkskomponenter.

docs: update framework components

---

packages/vue/htmlvalidate/rules/classdeprecated.rule.js
packages/vue/htmlvalidate/rules/classdeprecated.spec.ts
packages/vue/src/components/FFileItem/FFileItem.spec.ts
packages/vue/src/components/FFileItem/FFileItem.vue
packages/vue/src/components/FFileItem/__snapshots__/FFileItem.spec.ts.snap
packages/vue/src/cypress/FFileItem.pageobject.ts

https://forsakringskassan.github.io/designsystem/pr-preview/pr-564/components/file-upload/ffileitem.html

feat: remove `FFileItem` icon stack (fixes SFKUI-7249)

---

packages/design/src/components/message-box/_message-box.scss

Fixes #598.
https://forsakringskassan.github.io/designsystem/pr-preview/pr-603/components/table-and-list/table.html#felhantering

fix: table message box alignment errors (refs SFKUI-6500)

---

docs/functions/functions/assert-ref.md
docs/functions/functions/assert-set.md
etc/docs-manifest.md
etc/logic.api.md
packages/logic/src/assertions/assert-ref.spec.ts
packages/logic/src/assertions/assert-ref.ts
packages/logic/src/assertions/index.ts
packages/logic/src/index.ts

feat: add `assertRef` function (refs SFKUI-6500)

---

packages/design/src/components/calendar-day/_calendar-day.scss
packages/design/src/components/calendar-day/_variables.scss
packages/design/src/components/message-box/_message-box.scss
packages/design/src/components/message-box/_variables.scss
packages/design/src/components/wizard/_variables.scss
packages/design/src/components/wizard/_wizard-step.scss
packages/design/src/internal-components/calendar-navbar/_calendar-navbar.scss
packages/design/src/internal-components/calendar-navbar/_variables.scss

Added darkmode support for calendar, messagebox and wizard. Simplified visual design in wizard.

style: darkmode component updates (refs: SFKUI-6500)

---

docs/components/page-layout/FDetailsPanel.md
docs/components/page-layout/FFixedPane.md
docs/components/page-layout/FMinimizablePanel.md
docs/components/page-layout/FPageLayout.md
docs/components/page-layout/FResizePane.md

Mindre textändringar i de nya komponenterna för applikationslayout.

docs: update page layout (refs SFKUI-6500)

---

cypress/e2e/FWizardStep.cy.ts
docs.config.js
docs/functions/functions/modal-functions/form-modal.md
docs/functions/plugins/ErrorPlugin.md
packages/logic/src/converters/BankgiroConverter/bankgiroConverter.ts
packages/logic/src/converters/NumberConverter/numberConverter.ts
packages/logic/src/converters/OrganisationsnummerConverter/organisationsnummerConverter.ts
packages/logic/src/converters/PersonnummerConverter/personnummerConverter.ts
packages/logic/src/converters/PlusgiroConverter/plusgiroConverter.ts
packages/logic/src/converters/PostalCodeConverter/postalCodeConverter.ts
packages/logic/src/services/ValidationService/FieldsetValidationHandler.ts
packages/logic/src/services/ValidationService/Validators/IntegerValidator.ts
packages/logic/src/services/ValidationService/Validators/PercentValidator.ts
packages/logic/src/utils/DateUtils.ts
packages/logic/src/utils/test-luhn-checksum.ts
packages/test-utils/src/utils/generate-selector.ts
packages/vue-labs/src/components/XTimeTextField/utils/constants.ts
packages/vue/src/components/FCheckboxField/FCheckboxField.vue
packages/vue/src/components/FDetailsPanel/use-details-panel.ts
packages/vue/src/components/FIcon/examples/FIconAll.vue
packages/vue/src/components/FInteractiveTable/FInteractiveTable.vue
packages/vue/src/components/FInteractiveTable/useExpandableTable.ts
packages/vue/src/components/FLayoutRightPanel/FLayoutRightPanel.vue
packages/vue/src/components/FList/FList.vue
packages/vue/src/components/FPageLayout/FPageLayout.ce.vue
packages/vue/src/components/FTooltip/use-horizontal-offset.ts
packages/vue/src/components/FWizard/FWizardStep.vue
packages/vue/src/config/ButtonOrder.cy.ts
packages/vue/src/internal-components/IPopupError/IPopupError.vue
packages/vue/src/utils/event-bus.ts

more refactoring
